---
title: "Intro to ReadXL"
author: "Jeff Manson"
date: December 7, 2019
output: html_document
---

# Learning `readxl`


We are working with datain readxl and it's going to be amazing

Using the the following packages

- tidyverse
- readxl
- writexl
- here


```{r packages}
library(tidyverse)
library(readxl)
library(writexl)
library(here)
```

### Read in Fish Counts

```{r readCVS}
### Read in fish_counts_curated.csv 
fish_counts <- read_csv(here("R-workshop-data","fish_counts_curated.csv"))
```

### Read in data from a single excel worksheet in a workbook
```{r readExcelFile}
substrate_cover <- read_excel(here("R-workshop-data","substrate_cover_curated.xlsx"),skip =4, na = "-9999")

```

### Read a range from an excel document
```{r}
carp_cover_2000 <- read_excel(here("R-workshop-data","substrate_cover_curated.xlsx"),
                         range = "D12:I15",
                         col_names = c("site",
                                       "transect","quad","side",
                                       "type","coverage")
                         )
```

### Reading in data from Excel workbook with multiple worksheets
```{r}
kelp_counts <- read_excel(here("R-workshop-data","kelp_counts_curated.xlsx"),
                          sheet = "golb"
                         )
```


